### ISSUE TITLE
Joining Microsoft account for business

### ISSUE THREAD

**Issue by fantomdew** [memstechtips/UnattendedWinstall#12]
I have used the base unattended file to make a couple machines i was hoping to use for work. We do, however, have a need to join these machines to our AzureAD. When i try to join the machine to the AD it just hangs and after awhile errors out. Can you point me in the right direction as to what might need to be commented out for that to work?

**Comment by memstechtips** [comment]
Okay that could be a little tricky because I'm removing a lot of the telemetry stuff that's most probably needed for that to work.
What I would suggest is that you take some time to generate your own file using this generator https://schneegans.de/windows/unattend-generator/

You'll have more control over what gets removed and it will probably a lot better in a work environment.
