### ISSUE TITLE
The installer says can not find software license terms and then I am not able to continue the install process win 11 home

### ISSUE THREAD

**Issue by Tim-Schwalbe** [memstechtips/UnattendedWinstall#134]
The installer says can not find terms and then I am not able to continue the install process win 11 home.

![image](https://github.com/user-attachments/assets/bb7aeff5-ed6f-4188-b9cb-38a13443ce51)

**Comment by memstechtips** [comment]
Hey there,

This should be fixed in v2.0.0 - https://github.com/memstechtips/UnattendedWinstall/releases/tag/v2.0.0
In v2.0.0 Windows Pro is installed by default, if you want to install Home, you need to replace all instances in the file that looks like this:
```<Key>VK7JG-NPHTM-C97JM-9MPGT-3V66T</Key>```

with this

```<Key>YTMG3-N6DKC-DKB77-7M9GH-8HVX7</Key>```

Feel free to reopen the issue if it's not fixed.
