### ISSUE TITLE
How to manage update policies

### ISSUE THREAD

**Issue by BosuThau** [memstechtips/UnattendedWinstall#137]
![{2E86F9B7-57B0-4D73-A8DA-572C2E7C0D20}](https://github.com/user-attachments/assets/ea4882b7-b2a5-4f40-904c-7f1310e859e4)

Can't I manage these group policies made by your script? Can't find any info anywhere about this problem.

I want to install feature update kb5041587 and I get this message:

![{134035CB-37EB-4E1B-89BF-26779F31A4F9}](https://github.com/user-attachments/assets/af2d9768-1620-4073-ac56-c8fa70a5000f)

**Comment by leeuniverse** [comment]
I just removed his "Update" code section....  I just set the Group Policy Editor update related settings myself, since I like them different than he has set in this script.

To remove his changes, look in his script I think the Reg Entries, and then fix them in the Registry.
If I recall correctly, you can't change the Group Editor Policy settings if a setting has been changed in the Registry.  I think I encountered that, but I forget unsure.

**Comment by memstechtips** [comment]
To fix this issue, you can now also download and run the `UWScript.ps1` file and select the default Windows Update settings.
