### ISSUE TITLE
How to change startup type for some services?

### ISSUE THREAD

**Issue by tungthechicken** [memstechtips/UnattendedWinstall#23]
For example, the Security Center service is set to manual, thus on every boot, Windows spits out an error notification. Going to Services, the option to change startup type is greyed out.
![Screenshot 2024-06-30 033754](https://github.com/memstechtips/UnattendedWinstall/assets/53591848/f10b6a0f-8b52-48c6-9b25-bc42466f9849)
![Screenshot 2024-06-30 033904](https://github.com/memstechtips/UnattendedWinstall/assets/53591848/72819985-7811-45c5-831f-7441557de7e2)

Even using PowerShell with admin rights, I still can't change it
![image](https://github.com/memstechtips/UnattendedWinstall/assets/53591848/380ee2a2-0170-48bc-84b7-a6c3a7025e3a)

Is there anything I can do to change startup type to Automatic without reinstalling Windows?

**Comment by memstechtips** [comment]
This was an issue pointed out by one of my Discord members, I have removed the command from the answer file as it could be causing security issues, you can see it in the [Changelog](https://github.com/memstechtips/UnattendedWinstall/blob/main/CHANGELOG.md)

Unfortunately, I couldn't find a way to change it once Windows is installed already, but that's not because of the answer file, Windows doesn't allow it, even on a stock Windows install you are not able to change it, so you will need to reinstall Windows with the new answer file unfortunately.

The default setting for the service on a stock install is Automatic(Delayed Start) and even with the default setting, it doesn't always start automatically, I don't know why.
