### ISSUE TITLE
No parameters are set for DefaultUser.

### ISSUE THREAD

**Issue by Fleepe** [memstechtips/UnattendedWinstall#40]
Sorry, maybe I don't understand something, but no parameters that should be added or changed in the _HKU\DefaultUser_ registry directory were changed.
I tried to do them manually by writing them on the command line and in powershell, for example:
`reg.exe add "HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v AppsUseLightTheme /t REG_DWORD /d 0 /f`
and it outputs this:
`Error: The parameter is specified incorrectly.`
But if I write instead of _DefaultUser **.DEFAULT**_ , as written in the registry, then everything will work successfully.
Is this intended to be the way it is?
Here is log file I found:
[wintweaks.log](https://github.com/user-attachments/files/16115816/wintweaks.log)
A translator was used, so there may be some inaccuracies.

**Comment by Fleepe** [comment]
Ok, thank you for your explanation. Now it all became clear to me.

**Comment by memstechtips** [comment]
Thanks for the clear explanation @youri-- , you are completely correct.
Another piece of interesting information for you guys is that although all of the registry entries are written into `C:\Users\Default\NTUSER.DAT` (You can load it into Regedit and inspect it in Windows) the exact entries with the correct values are not applied when creating a new user account.

For example, the `C:\Users\Default\NTUSER.DAT` file will have these values.
```
:: Enables Dark Mode
reg.exe add "HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v AppsUseLightTheme /t REG_DWORD /d 0 /f
reg.exe add "HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v ColorPrevalence /t REG_DWORD /d 0 /f
reg.exe add "HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v EnableTransparency /t REG_DWORD /d 1 /f
reg.exe add "HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Themes\Personalize" /v SystemUsesLightTheme /t REG_DWORD /d 0 /f
```

But when you create a new user the values are changed from 0 to 1, so Windows resets it somewhere.

Now, if you have a User account with all of the registry entries and values you want, and you copy that users `NTUSER.DAT` file and replace `C:\Users\Default\NTUSER.DAT` and then create a new user account, all of the values are properly set.

Just thought I'd mention that because I spent a lot of time testing it out.

**Comment by RePacked** [comment]
@memstechtips If the registry entries get reset when creating a new account, what is the reason to include all the registry changes in the answer file?

**Comment by memstechtips** [comment]
It's actually not really necessary then hey, will look at removing it and only including the `currentuser.cmd` file, unless I find another fix. Will see.
