### ISSUE TITLE
Error: Windows cannot read the <ProductKey> setting from the unattend answer file

### ISSUE THREAD

**Issue by umermasood** [memstechtips/UnattendedWinstall#49]
I just followed the instructions from your [new video ](https://youtu.be/pDEZDD_gEbo) to flash the Windows 11 image
For the unattend file I used the default [IoT-LTSC-Like](https://github.com/memstechtips/UnattendedWinstall/blob/main/IoT-LTSC-Like/autounattend.xml) image you've provided. When I boot up Windows I get an error which says "Windows cannot read the <ProductKey> setting from the unattend answer file" and then the system reboots.

This is what it looks like:
![Untitled](https://github.com/memstechtips/UnattendedWinstall/assets/70061645/67a0fbeb-7eb0-4f1e-a788-3ae4cf4c2ed3)

Apparently some other people have reported this issue in YouTube comments, maybe something is wrong with the unattend file so I am creating an issue here.

**Comment by memstechtips** [comment]
This is interesting, I just downloaded the latest Windows 11 23H2 ISO and downloaded the [IoT-LTSC-Like](https://github.com/memstechtips/UnattendedWinstall/blob/main/IoT-LTSC-Like/autounattend.xml) .xml file and used AnyBurn to create the ISO.

I am able to install Windows perfectly fine. 
I'm not sure what the issue can be.

**Comment by memstechtips** [comment]
@umermasood I have just updated all of the files on the main branch to fix the formatting issues.
Please test it again and report back.

**Comment by Exmon2513** [comment]
I tested the new file, still got the same error as this guy. I tested it with the standard file.

**Comment by memstechtips** [comment]
Someone on my Discord server just reported when using the Media Creation Tool to create the bootable USB, the file doesn't work.

They used AnyBurn+Ventoy and then it worked.
I also just tested using Rufus+Copying the .xml file to the usb flash drive and it worked.

**Comment by raeffer** [comment]
I have the same error using rufus and dragging and dropping the .xml file. I will try Ventoy method now and see if I have any joy.

**Comment by memstechtips** [comment]
Really interested to find out what's causing this issue because I haven't encountered it at all.

**Comment by memstechtips** [comment]
I just reproduced this issue and that is because of using the arm64 answer file on a x64/amd64 based system.
![1720699169426](https://github.com/memstechtips/UnattendedWinstall/assets/172593213/b8fd086a-bc64-4c52-b6c1-29ca98544ca4)

Each file has 2 versions:
IoT-LTSC-Like
[x64/amd64](https://github.com/memstechtips/UnattendedWinstall/blob/main/IoT-LTSC-Like/autounattend.xml)
[arm64](https://github.com/memstechtips/UnattendedWinstall/blob/main/IoT-LTSC-Like/arm64/autounattend.xml)

Standard
[x64/amd64](https://github.com/memstechtips/UnattendedWinstall/blob/main/Standard/autounattend.xml)
[arm64](https://github.com/memstechtips/UnattendedWinstall/blob/main/Standard/arm64/autounattend.xml)

Each file has a comment that states which file it is, ex:


I am aware that @umermasood linked the correct x64/amd64 file when creating this issue, but when he created the issue, there were formatting issues in the XML files. I have updated and fixed that since. From all of my tests with all of the files, they all work perfectly fine, but I think you guys might be using the wrong version for your hardware.

**Comment by raeffer** [comment]
I redownloaded the answer file and remade installation media with ventoy and can report everything went perfectly. My racing sim is eternally grateful!!

**Comment by memstechtips** [comment]
@raeffer Perfect! I'm closing this issue in that chase. Have fun!

**Comment by Tom21798** [comment]
I seem to still have this issue when trying this with windows 10
