### ISSUE TITLE
IoT-LTSC-Like doesn't work for Windows To Go on Rufus (but Rufus own option does work) for both Windows 10 and 11

### ISSUE THREAD

**Issue by ownchoice** [memstechtips/UnattendedWinstall#53]
Hi there, I have a problem because the file seems to not be working for my use case.

## Context:

I'm using:
- My host machine runs **Windows 11 Pro**
- **Rufus 4.5** portable
- The "Windows To Go" option in Rufus
- The **official ISOs** for Windows 10 (`Win10_22H2_EnglishInternational_x64v1`) and Windows 11 (`Win11_23H2_EnglishInternational_x64v2`) from the Microsoft website.
- **AnyBurn 6.1**
- **IoT-LTSC-Like** version of this repos' `autounattend.xml` file.
- GPT Partition Scheme

![7zFM_SUXbb3mtwg](https://github.com/user-attachments/assets/326922bf-87f4-4bd4-984f-a3bbb29ec732)
![rufus-4 5p_LsQsF8WHu9](https://github.com/user-attachments/assets/51e0081e-971b-4634-80c0-3f0677facd8c)
![rufus-4 5p_FKcYq5SJAl](https://github.com/user-attachments/assets/769df506-29d1-442f-b065-55dbafe2fdfa)
![rufus-4 5p_yyPjXpJmVx](https://github.com/user-attachments/assets/1b4fb8c3-96f5-4616-969d-118c50ec9629)

## Problem:

When I use the Rufus options that create its own autounattend.xml file, it works. Meaning, I can choose to avoid the account sign-in and create a local account automatically thanks to Rufus' autounattend file.

However, when I try to use the modified (with AnyBurn) official ISOs for Win 10 and Win 11 with the autounattend file (IoT-LTSC-Like) it seems to not be working at all, it doesn't do its job.

I tried several times, doing the whole process over and over but I never got it working. But the three times that I used the Rufus options (that  creates its own autounattend.xml) it worked like a charm.

**How can I debug what's going wrong?**

**Comment by memstechtips** [comment]
Hi there, the issue is most probably due to different phases of the Windows installation being used between a normal Windows install and Windows To Go. I am planning to look at Windows To Go answer files in the future, but for now here is what I suggest you do:

1. Create a Windows To Go drive with the Rufus options (the one that you say works)
2. Once the drive is created, do a search on it for `*.xml` and it will list all of the .xml files on the Windows To Go disk.
3. Now you should find an `unattend.xml` file that Rufus created.
4. Open it and compare the phases it uses to the phases in my answer file. Phases meaning `generalize` and `specialize` and so on. Most of the commands in my answer file run in the `specialize` phase, and I suspect for Windows To Go, it uses different phases.

Hope this helps!
