### ISSUE TITLE
No WiFi

### ISSUE THREAD

**Issue by MicaelJarniac** [memstechtips/UnattendedWinstall#73]
I just installed Windows 11 23H2 on a laptop using the IoT-LTSC-Like file, and WiFi is not working.

Related terms:
- WiFi
- Wi-Fi
- Wireless

**Comment by MicaelJarniac** [comment]
I connected it to an ethernet cable and ran some updates, and now the WiFi seems to work. It would be nice to work out of the box, though.

**Comment by memstechtips** [comment]
Hi there, it's not the answer file that's causing the wifi issue, it's because the Windows ISO doesn't have your specific WiFi driver included.

The workaround is either to:
1. Connect via Ethernet and download the WiFi driver (like you did)
2.  Or download the WiFi driver and save it on a USB Flash Drive. Once Windows is installed, you can install the driver from the USB flash drive.

There are other methods of including the driver in the Windows ISO file as well, but you'll have to do some research on that yourself.

Hope this helps.

**Comment by MicaelJarniac** [comment]
Thanks! I'm not installing Windows often, so I wasn't sure where this issue was coming from. With Linux, it almost always detects WiFi straight away, so I thought Windows would do too.

**Comment by vasendak** [comment]
Hey, had the same problem. Most Android phones have USB tethering function. Connect your phone on WiFi, connect the phone to the computer with cable. Default option is USB File transfer, but you can choose USB tethering, works like a charm
