### ISSUE TITLE
Whatsapp doesn't run in the background

### ISSUE THREAD

**Issue by ts0ra** [memstechtips/UnattendedWinstall#89]
Whatsapp window need to stay open to keep it running, if i try to minimize it or let it run in the background it will stop receiving message and notification stop working.

**Comment by memstechtips** [comment]
Hi there,

Other people have reported that this solves the issue:

1. Open Regedit
2. Navigate to
Computer\HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Windows\Explorer
3. Remove "DisableNotificationCenter" entry

**Comment by memstechtips** [comment]
Please see https://github.com/memstechtips/UnattendedWinstall/blob/main/TROUBLESHOOTING.md

**Comment by vmserver** [comment]
> Hi there,
> 
> Other people have reported that this solves the issue:
> 
> 1. Open Regedit
> 2. Navigate to
>    Computer\HKEY_CURRENT_USER\SOFTWARE\Policies\Microsoft\Windows\Explorer
> 3. Remove "DisableNotificationCenter" entry




Its actually not about the disabled notification center. even if you Re-enable it whatsapp still doesnt work in background, if we minimize the WhatsApp window, it stops receiving msgs and calls, as soon we maximize the WhatsApp window only then we can receive the msgs. It is because something restricting WhatsApp to run at BACKGROUND.  it'll be helfull if you can guide something.

**Comment by ts0ra** [comment]
> Please see https://github.com/memstechtips/UnattendedWinstall/blob/main/TROUBLESHOOTING.md

ok i might try this one hopefully it works

**Comment by ts0ra** [comment]
ok it fixed
